### ISSUE TITLE
WeatherIcon and WindIcon components are seperate for hours-days

### ISSUE THREAD

**Issue by 99RP** [Vaaarna/weather2.0#2]
`DCWeatherIcon.vue` and `HCWeatherIcon.vue` are identical - all of the code is entirely duplicate for both. The same component can be used in multiple places, so there is no need for two separate components.

Same goes for `HCWindIcon.vue` and `DCWindIcon.vue`

More information on this design principle [here](https://docs.getdbt.com/terms/dry#why-write-dry-code)

**Comment by Vaaarna** [comment]
ok
